apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: fdus.gabrielebaldoni.com
spec:
  group: gabrielebaldoni.com
  version: v1
  names:
    kind: FDU
    listKind: FDUList
    plural: fdus
    singular: fdu
  scope: Namespaced